Integrate xUnit testing in GitHub Actions workflow
This commit enhances the GitHub Actions workflow for the 'dev' branch by integrating xUnit testing into the CI/CD pipeline. The addition of the xUnit test step in the build job ensures that all unit tests are automatically executed each time new code is pushed, thereby maintaining code quality and stability.

Key Changes:
- A new test step using   Determining projects to restore...
  All projects are up-to-date for restore.
/Users/norahaltamimi/Desktop/AppDemo/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [/Users/norahaltamimi/Desktop/AppDemo/AppDemo.csproj]
/Users/norahaltamimi/Desktop/AppDemo/obj/Debug/net8.0/AppDemo.AssemblyInfo.cs(13,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [/Users/norahaltamimi/Desktop/AppDemo/AppDemo.csproj]
/Users/norahaltamimi/Desktop/AppDemo/obj/Debug/net8.0/AppDemo.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [/Users/norahaltamimi/Desktop/AppDemo/AppDemo.csproj]
/Users/norahaltamimi/Desktop/AppDemo/obj/Debug/net8.0/AppDemo.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute [/Users/norahaltamimi/Desktop/AppDemo/AppDemo.csproj]
/Users/norahaltamimi/Desktop/AppDemo/obj/Debug/net8.0/AppDemo.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute [/Users/norahaltamimi/Desktop/AppDemo/AppDemo.csproj]
/Users/norahaltamimi/Desktop/AppDemo/obj/Debug/net8.0/AppDemo.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [/Users/norahaltamimi/Desktop/AppDemo/AppDemo.csproj]
/Users/norahaltamimi/Desktop/AppDemo/obj/Debug/net8.0/AppDemo.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [/Users/norahaltamimi/Desktop/AppDemo/AppDemo.csproj]
/Users/norahaltamimi/Desktop/AppDemo/obj/Debug/net8.0/AppDemo.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [/Users/norahaltamimi/Desktop/AppDemo/AppDemo.csproj] has been added to the 'build' job, specifically running xUnit tests.
- The test step is configured to operate in the Release configuration, indicated by the  flag.
- Optimization is achieved by using the  flag in both the test and build steps, reducing redundant dependency restoration activities.